services:
  backend:
    build:
      context: .
    ports:
      - 3001:3001
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdb:/var/lib/postgresql/data

volumes:
  pgdb:
